"""initial migration

Revision ID: 5283c85c985d
Revises: 
Create Date: 2017-12-06 16:47:04.682801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5283c85c985d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('job_code', sa.String(length=30), nullable=True),
    sa.Column('is_incumbency', sa.SMALLINT(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesmen_job_code'), 'salesmen', ['job_code'], unique=False)
    op.create_index(op.f('ix_salesmen_username'), 'salesmen', ['username'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_salesman_id'), 'customers', ['salesman_id'], unique=False)
    op.create_index(op.f('ix_customers_telephone'), 'customers', ['telephone'], unique=True)
    op.create_table('customer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_records_customer_id'), 'customer_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_records_salesman_id'), 'customer_records', ['salesman_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_records_salesman_id'), table_name='customer_records')
    op.drop_index(op.f('ix_customer_records_customer_id'), table_name='customer_records')
    op.drop_table('customer_records')
    op.drop_index(op.f('ix_customers_telephone'), table_name='customers')
    op.drop_index(op.f('ix_customers_salesman_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_salesmen_username'), table_name='salesmen')
    op.drop_index(op.f('ix_salesmen_job_code'), table_name='salesmen')
    op.drop_table('salesmen')
    # ### end Alembic commands ###
